name: HTML Login Page Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test if index.html exists
      run: |
        if [ ! -f "index.html" ]; then
          echo "Error: index.html does not exist!" && exit 1
        else
          echo "index.html exists!"
        fi

    - name: Run other tests (optional)
      run: |

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy the HTML page (example)
      run: |
        echo "Deploying index.html..."
        echo "Deployment complete!"
